# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image:
    name: klakegg/hugo:ext-alpine
    entrypoint : ['']

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
